credentials:
  usernames:
    mariah:
      email: mariah@hotmail.com
      logged_in: False # Will be managed automatically
      name: Mariah
      password: mariah123 # Will be hashed automatically
    ricardo:
      email: ricardo@gmail.com
      logged_in: False # Will be managed automatically
      name: Ricardo
      password: ricardo123 # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - teste2121@hotmail.com